### PR TITLE
Rypb

### PR DESCRIPTION
**Pull request by ghost**
Hey there,

I really like the tool you've got here. I'm just getting comfortable with Python and so I figured I would contribute a bit to something I've used. It's not much - just some things that helped me understand the functions better - but I might be able to commit some actual code soon.

Thanks for making such a useful AWS enumerator!

### CODE REVIEW

**Comment by jordanpotti** [comment]
I think it would be nice to have Contributors listed in the index.md and have the rest of the contributors listed!

**Comment by ghost** [comment]
Agreed! I added them.

**Comment by jordanpotti** [comment]
Cool, instead of putting those in a separate file, could you just list them in index.md? It'd nice if you made them hyperlinks to their respective GitHub profiles as well :)

**Comment by ghost** [comment]
Done!

**Review by jordanpotti — APPROVED** [review]
Looks good!

**Pull request merged**
